name: CI Build/Test
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install
    - run: bun run test
    - run: bun run build
    - name: Convex Deploy
      if: github.ref == 'refs/heads/main' && env.CONVEX_DEPLOY_KEY != ''
      run: npx convex deploy
      env:
        CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY }}
      continue-on-error: true
